server:
  port: 8781

spring:
  #消息队列
  rabbitmq:
    host: 192.168.218.131
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  #zipkin服务地址
  zipkin:
    base-url: http://192.168.218.131:9411/
  #配置采样百分比,开发环境可以设置为1,表示全部采样,生产就用默认的0.1比例采样
  sleuth:
    sampler:
      probability: 1

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#配置连接超时,启动hystrix
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 4000
  hystrix:
    enabled: true

hystrix:
  #把hystrix超时时间禁用(不推荐)
  #    command:
  #      default:
  #        execution:
  #          timeout:
  #            enabled: true
  #设置超时时间
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#暴露所有的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
