server:
  port: 8771

#消息队列
spring:
  rabbitmq:
    host: 172.30.25.166
    port: 5672
    username: guest
    password: guest
 
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env: dev
branch: master
